FROM python:3.10-slim

WORKDIR /app

RUN apt-get update && apt-get install -y build-essential \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy Python scripts
COPY src/ ./

# copy data
COPY data ./data

# run main.py
CMD ["python", "main.py"]
